"""init

Revision ID: 7fad43a48ba3
Revises: 
Create Date: 2024-02-25 17:29:37.024046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fad43a48ba3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mkds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('cad_id', sa.String(), nullable=False),
    sa.Column('address_id', sa.String(), nullable=False),
    sa.Column('total_area', sa.Float(), nullable=True),
    sa.Column('total_flats_area', sa.Float(), nullable=True),
    sa.Column('year_of_building', sa.Integer(), nullable=True),
    sa.Column('way_of_administration', sa.String(), nullable=True),
    sa.Column('management_organisation_inn', sa.Integer(), nullable=True),
    sa.Column('rso_inn', sa.String(), nullable=True),
    sa.Column('house_view_link', sa.String(), nullable=True),
    sa.Column('orgs_link', sa.String(), nullable=True),
    sa.Column('passport_link', sa.String(), nullable=True),
    sa.Column('region_code', sa.Integer(), nullable=True),
    sa.Column('postal_code', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('building_number', sa.String(), nullable=True),
    sa.Column('cad_num_mkd', sa.String(), nullable=True),
    sa.Column('yandex_maps_link', sa.String(), nullable=True),
    sa.Column('floors_count', sa.Integer(), nullable=True),
    sa.Column('entrances_count', sa.Integer(), nullable=True),
    sa.Column('elevators_count', sa.Integer(), nullable=True),
    sa.Column('land_cad_id', sa.String(), nullable=True),
    sa.Column('land_area', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('organization_inn', sa.Integer(), nullable=False),
    sa.Column('executor_status', sa.String(), nullable=False),
    sa.Column('organization_name', sa.String(), nullable=False),
    sa.Column('region_name', sa.String(), nullable=False),
    sa.Column('orgn', sa.Integer(), nullable=False),
    sa.Column('registered_date', sa.Date(), nullable=True),
    sa.Column('kpp', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('contacting_phone', sa.String(), nullable=True),
    sa.Column('dispatcher_phone', sa.String(), nullable=True),
    sa.Column('director_names', sa.String(), nullable=True),
    sa.Column('director_post', sa.String(), nullable=True),
    sa.Column('all_functions', sa.String(), nullable=True),
    sa.Column('organization_view_link', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('organization_name_short', sa.String(), nullable=True),
    sa.Column('ogrn_dadata', sa.Integer(), nullable=True),
    sa.Column('eio_names', sa.String(), nullable=True),
    sa.Column('eio_post', sa.String(), nullable=True),
    sa.Column('phone_dadata', sa.String(), nullable=True),
    sa.Column('email_dadata', sa.String(), nullable=True),
    sa.Column('dadata_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('organization_inn')
    )
    op.create_table('partitions',
    sa.Column('partition_code', sa.Integer(), nullable=False),
    sa.Column('partition_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('partition_code')
    )
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', 'SUPER_ADMIN', name='userrolesenum'), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('duoss',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mkd', sa.String(), nullable=False),
    sa.Column('partition', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('document_number', sa.String(), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('mkd_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mkd'], ['mkds.id'], ),
    sa.ForeignKeyConstraint(['partition'], ['partitions.partition_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mkd_id', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('cad_id', sa.String(), nullable=False),
    sa.Column('statutory_number', sa.String(), nullable=True),
    sa.Column('total_area', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('living_area', sa.Float(), nullable=True),
    sa.Column('rooms_count', sa.Integer(), nullable=True),
    sa.Column('entrance_number', sa.Integer(), nullable=True),
    sa.Column('is_emergency', sa.Boolean(), nullable=True),
    sa.Column('reestr', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('room_number', sa.String(), nullable=True),
    sa.Column('cadnum', sa.String(), nullable=True),
    sa.Column('fias_code', sa.String(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('fias_level', sa.String(), nullable=True),
    sa.Column('id_mkd', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mkd_id'], ['mkds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_datetime', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('rooms')
    op.drop_table('duoss')
    op.drop_table('users')
    op.drop_table('partitions')
    op.drop_table('organizations')
    op.drop_table('mkds')
    # ### end Alembic commands ###
